
[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/accommodations"
  to = "/accommodations.html"
  status = 200

[[redirects]]
  from = "/things-to-do"
  to = "/things-to-do.html"
  status = 200

[[redirects]]
  from = "/where-to-eat"
  to = "/where-to-eat.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200
